name : Node.js CI/CD Pipeline

on:
  push:
    branches: [ main ]

jobs:
  build:
    name: Build Node App
    runs-on: ubuntu-latest 
    steps:
    - name: Checkout code
      uses: actions/checkout@v2

    - name: Sey up Node.js 
      uses : actions/setup-node@v3
      with:
        node-version: '18'
    
    - name: Install dependencies
      run : npm install 

  docker:
    name: Dockerize and Push 
    needs: build
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      - name: Login to Docker Hub
        uses: docker/login-action@v2 
        with:
          username: ${{ secrets.DOCKERHUB_USERNAME }}
          password: ${{ secrets.DOCKERHUB_TOKEN }}

      - name: Build and push image to Docker Hub
        run : |
          docker build -t ${{ secrets.DOCKERHUB_USERNAME }}/node.app:latest .
          docker push ${{ secrets.DOCKERHUB_USERNAME }}/node.app:latest

